[[plugins]]
repo = 'kazuph/previm'
on_ft=['markdown']
rev = 'feature/add-plantuml-plugin'
hook_add = '''
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
'''
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i =1

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft=['markdown']


[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
hook_add = '''
if !exists('g:neocomplete#text_mode_filetypes')
    let g:neocomplete#text_mode_filetypes = {}
endif
let g:neocomplete#text_mode_filetypes = {
            \ 'rst': 1,
            \ 'markdown': 1,
            \ 'gitrebase': 1,
            \ 'gitcommit': 1,
            \ 'vcs-commit': 1,
            \ 'hybrid': 1,
            \ 'text': 1,
            \ 'help': 1,
            \ 'tex': 1,
            \ 'python': 1,
            \ }
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft= 'python'
hook_add = '''
    let g:jedi#use_tabs_not_buffers = 1 
    let g:jedi#popup_select_first=0 
    let g:jedi#popup_on_dot=0
""    let g:jedi#goto_command = "<leader>d"
""    let g:jedi#goto_assignments_command = "<leader>g"
""    let g:jedi#goto_definitions_command = ""
""    let g:jedi#documentation_command = "K"
""    let g:jedi#usages_command = "<leader>n"
""    let g:jedi#rename_command = "<leader>R"
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#completions_enabled = 0
    let g:jedi#show_call_signatures = 0
    autocmd FileType python setlocal completeopt-=preview 
'''
